// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgKPdOmGqt6h0WdNWUdPvTM7D1wUTekrk',
    appId: '1:591831940582:web:7f6bfe5397b48771da6a27',
    messagingSenderId: '591831940582',
    projectId: 'projek-mpp-anime-list',
    authDomain: 'projek-mpp-anime-list.firebaseapp.com',
    storageBucket: 'projek-mpp-anime-list.appspot.com',
    measurementId: 'G-PHV5NHJLL7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5H1x_zTPYUA_WSLw6jfMLPWdIS1zS19Y',
    appId: '1:591831940582:android:45dbda436bd6312fda6a27',
    messagingSenderId: '591831940582',
    projectId: 'projek-mpp-anime-list',
    storageBucket: 'projek-mpp-anime-list.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBo5IiVuurE01ddUOXw0g-cJjW2GSYOOw',
    appId: '1:591831940582:ios:03430fcf043fee78da6a27',
    messagingSenderId: '591831940582',
    projectId: 'projek-mpp-anime-list',
    storageBucket: 'projek-mpp-anime-list.appspot.com',
    iosClientId: '591831940582-9tn0n1dabm6f4u9j8l7g3amk0l0nrjt0.apps.googleusercontent.com',
    iosBundleId: 'com.example.animeList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBo5IiVuurE01ddUOXw0g-cJjW2GSYOOw',
    appId: '1:591831940582:ios:03430fcf043fee78da6a27',
    messagingSenderId: '591831940582',
    projectId: 'projek-mpp-anime-list',
    storageBucket: 'projek-mpp-anime-list.appspot.com',
    iosClientId: '591831940582-9tn0n1dabm6f4u9j8l7g3amk0l0nrjt0.apps.googleusercontent.com',
    iosBundleId: 'com.example.animeList',
  );
}
